apiVersion: v1
kind: Pod
metadata:
  name: glusterfs
spec:
  containers:
  - name: glusterfs
    image: ubuntu
    command:
      - sleep
      - "3600"
    volumeMounts:
      - name: glusterfsvol
        mountPath: /mnt/glusterfs
  volumes:
  - name: glusterfsvol
    glusterfs:
      endpoints: glusterfs-cluster
      path: repl
