apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway
        tier: training
    spec:
      containers:
      - name: gateway
        image: 192.168.221.20:5000/han/gateway:0.1
        command:
          - /gateway/gateway
          - --endpoint=outer-grpc-service:8081
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 10000
          protocol: TCP
