apiVersion: v1
kind: Service
metadata:
  name: dfs
  labels:
    app: dfssvr
    tier: dfssvr
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '1920'
    prometheus.io/dfssvr: 'ok'
spec:
  type: NodePort
  ports:
  - name: dfs
    port: 10000
    nodePort: 32000
    targetPort: 10000
    protocol: TCP
  - name: metrics                                                                                        
    port: 1920
    targetPort: 1920
    protocol: TCP
  selector:
    name: dfssvr
    tier: dfssvr
