apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skylb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: skylb
        tier: backend
    spec:
      containers:
      - name: skylb
        image: docker-registry.eff.com/skylb/skylb:1.0
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        command:
          - /skylb/bin/skylb
          - --etcd-endpoints=http://192.168.221.120:3379
          - --alsologtostderr
          - --v=3
        ports:
        - containerPort: 9000
          protocol: TCP

