kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus-skylb
  name: prometheus-skylb
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus-skylb

