apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skylb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: skylb
        tier: skylb
    spec:
      containers:
      - name: skylb
        image: docker-registry.eff.com/skylb/skylb:1.0
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 1900
          protocol: TCP
        - containerPort: 1920
          protocol: TCP
        env:
        - name: WITHIN_K8S
          value: "true"
        - name: ENDPOINTS
          value: "http://192.168.10.60:3379"
        - name: LOG_LEVEL
          value: "3"
        - name: LOG_DIR
          value: "/tmp"
