apiVersion: v1
kind: Service
metadata:
  name: skylb
  labels:
    app: skylb
    tier: skylb
spec:
  type: NodePort
  ports:
  - name: skylb
    port: 1900
    targetPort: 1900
    nodePort: 31900
    protocol: TCP
  - name: metrics
    port: 1920
    targetPort: 1920
    nodePort: 31920
    protocol: TCP
  selector:
    name: skylb
    tier: skylb
