apiVersion: v1
kind: Pod
metadata:
  name: pgsecret
spec:
  containers:
  - name: pgsecret
    image: ubuntu
    command:
      - sleep
      - "3600"
    volumeMounts:
      - name: pg-secret-vol
        mountPath: /etc/secret
        readOnly: true
  volumes:
  - name: pg-secret-vol
    secret:
      secretName: pgsecret
