apiVersion: v1
kind: Service
metadata:
  name: mottos-be-han
  labels:
    app: mottos-be-han
    tier: training
spec:
  ports:
  - name: mottosbe
    port: 9100
    targetPort: "mottosbe"
  selector:
    name: mottos-be-han
    tier: training
