kind: Service
apiVersion: v1
metadata:
  labels:
    app: prom4dfs
  name: prom4dfs
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prom4dfs

